version: '2'
services:
  zookeper:
    build: zookeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  
  broker:
    build: broker
    depends_on:
      - zookeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeper:2181

  flask-streamer:
    build: flask-streamer
    ports:
      - 5000:5000
    depends_on:
      - spark
    environment: 
      KAFKA_BROKER: broker:9092

  spark:
    build: spark
    depends_on: 
      - broker
    ports:
      - 9999:9999
    environment:
      KAFKA_BROKER: broker:9092
      MONGO_SERVER: mongo:27017
      MONGO_PORT: 27017

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

